FROM node:18
WORKDIR /usr/src/app

# Kopieer alleen de package.json bestanden eerst
COPY package*.json ./
RUN npm install

# Kopieer nu de rest van de applicatie
COPY . .

# Gebruik een omgevingsvariabele voor de poort (met standaardwaarde 3000)
EXPOSE ${BACKEND_PORT:-3000}
CMD ["node", "src/app.js"]
